apiVersion: v1
kind: Service
metadata:
  name: flask-login-service
  labels:
    app: flask-login
spec:
  type: ClusterIP
  selector:
    app: flask-login
  ports:
    - port: 80
      targetPort: 5000
